# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Electron Build CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: master-electron

jobs:
  # This job will archive the next server
  archiving-next-build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Electron
        uses: actions/checkout@v2

      - name: Checkout NextJS submodule
        run: git submodule update --init -- next

      - name: Use Node.js ${{ matrix.node-version }}, NPM and Yarn
        working-directory: ./next
          # uses: actions/setup-node@v2
          # with:
        # node-version: ${{ matrix.node-version }}
        # cache: 'npm'
        run: 'npm install'

      - name: Build next
        working-directory: ./next
          # uses: actions/setup-node@v2
          # with:
        # node-version: ${{ matrix.node-version }}
        # cache: 'npm'
        run: 'npm run build'

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'next.zip'
          directory: './next'
          exclusions: '*.env* .editorconfig'

  # Create the electron build for windows and macOS
  electron-build:
    runs-on: ${{ matrix.os }}
    environment: production
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [ 14.x ]
        os: [ windows-latest, macos-latest ]

    needs: [ archiving-next-build ]

    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # custom script with need to run
          build_script_name: "build:electron:prod"

          args: "-p always"

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
