# This is a basic workflow to help you get started with Actions

name: Create Archive

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: master-electron

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: windows-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout Electron
              uses: actions/checkout@v2
              
            - name: Checkout NextJS submodule
              uses: textbook/git-checkout-submodule-action@master
            
            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                  type: 'zip'
                  filename: 'release.zip'
                  directory: './next'
                  exclusions: '*.env* .editorconfig'
